services:
    api:
        build: .
        env_file:
            - .env
        environment:
            DATABASE_URL: postgresql+psycopg://expense_user:33338020@db:5432/expense_tracker
            TEST_DATABASE_URL: postgresql+psycopg://expense_user:33338020@db:5432/expense_tracker_test
            REDIS_HOST: redis
        ports:
            - "8000:8000"

    db:
        image: postgres:17
        environment:
            POSTGRES_USER: expense_user
            POSTGRES_PASSWORD: 33338020
            POSTGRES_DB: expense_tracker
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./docker/postgres/init:/docker-entrypoint-initdb.d

    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"

volumes:
    postgres_data:
