"""add role column to users

Revision ID: 4fa98cb2f336
Revises: 29b1ac3cf68c
Create Date: 2026-08-03 13:03:13.395911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa98cb2f336'
down_revision: Union[str, Sequence[str], None] = '29b1ac3cf68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
